apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - audiobookshelf.yaml
  - calibre-web-with-importer.yaml
  - bookorbit.yaml
  - bookhoarder.yaml
  - booklogr.yaml
  - librislog.yaml
  - immich.yaml
  - immich-pdb.yaml
  - immich-db-backup.yaml
  - flick.yaml
  - pgweb.yaml
