# MSSQL Service
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: iiqstack
  labels:
    app: mssql
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: 1433
      protocol: TCP
      name: mssql
  selector:
    app: mssql

---
# MSSQL StatefulSet  
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  namespace: iiqstack
  labels:
    app: mssql
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
              name: mssql
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Developer"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: mssql-sa-password
          volumeMounts:
            - name: mssql-storage
              mountPath: /var/opt/mssql
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          readinessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: mssql-data-pvc