apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: iiqstack
type: Opaque
stringData:
  mssql-sa-password: "id3ntityIQ!-TQ8BaiOxKAL4v-4lCIxVx"
  mssql-user-password: "id3ntityIQ!-TQ8BaiOxKAL4v-4lCIxVx"
  mysql-root-password: "password"
  mysql-user-password: "identityiq"
  ldap-admin-password: "spadmin"
  ssh-password: "password"