apiVersion: v1
kind: Service
metadata:
  name: counter
  labels:
    app: counter
spec:
  type: ClusterIP
  ports:
    - port: 12345
      targetPort: 12345
      protocol: TCP
      name: http
  selector:
    app: counter