apiVersion: apps/v1
kind: Deployment
metadata:
  name: iiq
  labels:
    app: iiq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iiq
  template:
    metadata:
      labels:
        app: iiq
    spec:
      initContainers:
        - name: wait-for-hr-table
          image: mysql:8.0
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for MySQL to be available at db-mysql:3306..."
              until mysqladmin ping -hdb-mysql -uidentityiq -pidentityiq --silent; do
                echo "MySQL not up yet..."
                sleep 5
              done
              echo "Checking for hr database..."
              until mysql -hdb-mysql -uidentityiq -pidentityiq -e "USE hr;" ; do
                echo "hr database not found yet..."
                sleep 5
              done
              echo "Checking for hr_people table in hr database..."
              until mysql -hdb-mysql -uidentityiq -pidentityiq -e "USE hr; DESCRIBE hr_people;" ; do
                echo "hr_people table not found yet..."
                sleep 5
              done
              echo "MySQL, hr database, and hr_people table are ready."
      containers:
        - name: iiq
          image: 192.168.0.236:5000/sailpoint-docker:latest
          env:
            - name: DATABASE_TYPE
              value: "mssql"
            - name: MSSQL_HOST
              value: "db"
            - name: MSSQL_SA_USER
              value: "sa"
            - name: MSSQL_USER
              value: "identityiq"
            - name: MSSQL_PASS
              value: "id3ntityIQ!-TQ8BaiOxKAL4v-4lCIxVx"
            - name: MSSQL_SA_PASSWORD
              value: "id3ntityIQ!-TQ8BaiOxKAL4v-4lCIxVx"
            - name: MYSQL_HOST
              value: "db_mysql"
            - name: MYSQL_USER
              value: "identityiq"
            - name: MYSQL_PASSWORD
              value: "identityiq"
            - name: MYSQL_DATABASE
              value: "identityiq"
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: CATALINA_OPTS
              value: "-Xmx2048M"