apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iiq-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /identityiq
            pathType: Prefix
            backend:
              service:
                name: iiq
                port:
                  number: 8080