apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      enableServiceLinks: false
      containers:
        - name: ldap
          image: osixia/openldap:1.5.0
          ports:
            - containerPort: 389
          env:
            - name: LDAP_DOMAIN
              value: "sailpoint.demo"
            - name: LDAP_ORGANISATION
              value: "Sailpoint Demo"
            - name: LDAP_ADMIN_PASSWORD
              value: "spadmin"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: ldap-persistent-storage
              mountPath: /var/lib/ldap # This is where OpenLDAP stores its data
            - name: ldap-config-storage # Mount for LDAP configuration files
              mountPath: /etc/ldap/slapd.d
      volumes:
        - name: ldap-persistent-storage
          persistentVolumeClaim:
            claimName: ldap-pvc # Reference the PVC we created earlier
        - name: ldap-config-storage
          persistentVolumeClaim:
            claimName: ldap-config-pvc


