apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  labels:
    app: loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
  selector:
    app: loadbalancer