# Traefik Service
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  namespace: iiqstack
  labels:
    app: traefik
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: web
    - port: 8080
      targetPort: 9000
      protocol: TCP
      name: dashboard
  selector:
    app: traefik

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: iiqstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-sa
      terminationGracePeriodSeconds: 60
      containers:
        - name: traefik
          image: traefik:v2.9
          imagePullPolicy: IfNotPresent
          args:
            - "--api.insecure=true"  # Enable insecure dashboard access
            - "--providers.kubernetescrd"  # Enable Kubernetes CRD provider
            - "--entrypoints.web.address=:80"  # HTTP entrypoint
            - "--entrypoints.websecure.address=:443"  # HTTPS entrypoint
            - "--ping"                # Enable health check endpoint
            - "--entrypoints.traefik.address=:9000"  # Traefik dashboard entrypoint
            - "--providers.kubernetesingress"  # Enable Kubernetes Ingress provider
            - "--log.level=DEBUG"  # Access log file path 
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: dashboard
              containerPort: 9000     # Only expose internally
          readinessProbe:
            httpGet:
              path: /ping
              port: dashboard
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /ping
              port: dashboard
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
