apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-counter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-counter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%    # max 25% of Pods can be unavailable during the update
      maxSurge: 25% 
  template:
    metadata:
      labels:
        app: docker-counter
    spec:
      containers:
      - name: docker-counter
        image: drosenbauer/docker-counter
        ports:
        - containerPort: 54321
        env:
        - name: PORT
          value: "54321"
---
apiVersion: v1
kind: Service
metadata:
  name: docker-counter-service
spec:
  type: NodePort
  selector:
    app: docker-counter
  ports:
  - protocol: TCP
    port: 54321
    targetPort: 54321
    nodePort: 30021  # optional: manually pick a port between 30000–32767
