apiVersion: v1
kind: Service
metadata:
  name: counter
  namespace: iiqstack
  labels:
    app: counter
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: counter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  namespace: iiqstack
  labels:
    app: counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
        - name: counter
          image: drosenbauer/docker-counter
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: counter-data
              mountPath: /data
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: counter-data
          emptyDir: {}