apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freelingo-ingress
  namespace: freelingo
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: freelingo.example.com
      http:
        paths:
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: freelingo-backend
                port:
                  number: 8000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: freelingo-backend
                port:
                  number: 8000
          - path: /health
            pathType: Exact
            backend:
              service:
                name: freelingo-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: freelingo-frontend
                port:
                  number: 3000
