kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: freelingo-backend-data
  namespace: freelingo
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freelingo-db-data
  namespace: freelingo
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freelingo-redis-data
  namespace: freelingo
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
