apiVersion: v1
kind: ServiceAccount
metadata:
  name: freelingo-backend
  namespace: freelingo
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: freelingo-frontend
  namespace: freelingo
automountServiceAccountToken: false
