apiVersion: v1
kind: Service
metadata:
  name: freelingo-tailscale
  namespace: freelingo
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/proxy-class: "tailscale-proxy"
    tailscale.com/hostname: "freelingo"
spec:
  type: ClusterIP
  selector:
    app: freelingo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
