apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-backup-target-settings.yaml
  - 02-recurring-jobs.yaml
  - 03-filesystem-trim-optional.yaml
  - 04-node-failure-resilience.yaml
  - 05-storage-reserve.yaml
  - 06-storageclass-r1.yaml
  - 07-nfs40-premount.yaml
